package com.flowdeck.util;

import java.util.List;

/**
 * Generates lexicographically-sortable rank strings for ordering
 * {@code Card}s within a {@code BoardList} (and {@code BoardList}s within a
 * {@code Board}) — see {@code Card.rank} for the full rationale for using a
 * string rank instead of an integer position.
 *
 * <h2>The algorithm</h2>
 *
 * A rank is treated as a base-36 fraction: each character is a "digit" from
 * {@link #ALPHABET} (0-9 before a-z, so plain byte-string comparison — what
 * Postgres does for {@code ORDER BY} on a {@code varchar} — agrees with the
 * intended order), and a shorter string sorts as if padded with the lowest
 * digit ({@code '0'}) forever. {@link #between} finds a value strictly
 * between two ranks by walking the two inputs digit-by-digit, at each
 * position comparing {@code lo} (the digit of {@code prev}, or {@code 0}
 * once {@code prev} runs out) against {@code hi} (the digit of {@code next},
 * or one-past-the-end — "infinity" — once {@code next} runs out or is
 * absent):
 *
 * <ul>
 *   <li>If there's a free digit strictly between {@code lo} and {@code hi}
 *       at this position ({@code hi - lo > 1}), take its midpoint, append
 *       it, and stop — the result sorts strictly between the inputs.</li>
 *   <li>Otherwise there's no room yet at this depth: carry {@code lo}
 *       forward (the shared prefix so far) and go one digit deeper.</li>
 * </ul>
 *
 * This is the technique behind LexoRank / Trello-style position strings.
 * {@code between(null, next)} places before everything (drag to the very
 * top); {@code between(prev, null)} places after everything (drag to the
 * bottom, or the first item in an empty list); {@code between(prev, next)}
 * places between two existing siblings.
 *
 * <h2>Rank exhaustion and rebalancing</h2>
 *
 * Because a rank can always grow another digit, there is no input pair
 * {@code between} can't technically solve — but letting it grow forever is
 * bad practice (ever-longer strings cost more storage and slower
 * comparisons), so this class draws a practical line: {@link #between}
 * refuses to return a rank longer than {@link #MAX_RANK_LENGTH}, throwing
 * {@link RankExhaustionException} instead. That happens only when many
 * inserts in a row have targeted the exact same gap — e.g. someone
 * repeatedly dragging a card to sit in exactly the same spot — which is the
 * worst case for this algorithm (every other access pattern grows ranks far
 * more slowly, close to one extra character per O(log₃₆ n) inserts, not per
 * insert). At {@code MAX_RANK_LENGTH = 12}, reaching that worst case takes
 * roughly 55 consecutive same-gap inserts; see {@code RankGeneratorTest} for
 * the simulation this number comes from.
 *
 * <p>The fix is not to make ranks longer — it's to reset the list to short,
 * evenly-spaced ranks. {@link #spacedRanks} does exactly that: given a
 * count, it returns that many ranks in order, generated by recursively
 * bisecting the whole rank space (find the middle item's rank first, then
 * recurse on each half) rather than sequentially, which keeps every result
 * within O(log₃₆ count) characters — for any realistic list size, just a
 * handful. A caller — see {@code com.flowdeck.service.CardService} — catches
 * {@link RankExhaustionException}, rebalances the affected list with
 * {@link #spacedRanks}, and retries the original {@link #between} call
 * against the freshly spaced neighbours.
 */
public final class RankGenerator {

    /**
     * Ascending digit order. Digits before letters matters: it means plain
     * ASCII/byte string comparison (what {@code ORDER BY} on a Postgres
     * {@code text}/{@code varchar} column does under the default "C"-like
     * collation for this alphabet) agrees with the intended rank order.
     */
    private static final String ALPHABET = "0123456789abcdefghijklmnopqrstuvwxyz";
    private static final int BASE = ALPHABET.length();

    /** One past the last valid digit index — stands in for "infinity" when a bound is absent. */
    private static final int INFINITY = BASE;

    /**
     * Longest rank {@link #between} will produce before giving up and
     * signalling exhaustion — see the class Javadoc "Rank exhaustion" section
     * for how this number was chosen. {@code VARCHAR(255)} in the schema
     * leaves enormous headroom beyond this; the limit exists to keep ranks
     * short in the common case, not because the column would run out.
     */
    public static final int MAX_RANK_LENGTH = 12;

    private RankGenerator() {}

    /** Rank for the first item ever inserted into an empty list. */
    public static String initial() {
        return between(null, null);
    }

    /**
     * A rank that sorts strictly after {@code prev} and strictly before
     * {@code next}.
     *
     * @param prev the preceding sibling's rank, or {@code null} for "insert at the start"
     * @param next the following sibling's rank, or {@code null} for "insert at the end"
     * @throws IllegalArgumentException if {@code prev} is not strictly less than {@code next}
     * @throws RankExhaustionException if no rank within {@link #MAX_RANK_LENGTH}
     *     characters sorts between them — the caller should rebalance the
     *     surrounding list (see {@link #spacedRanks}) and retry
     */
    public static String between(String prev, String next) {
        if (prev != null && next != null && prev.compareTo(next) >= 0) {
            throw new IllegalArgumentException(
                    "prev ('%s') must sort before next ('%s')".formatted(prev, next));
        }

        StringBuilder result = new StringBuilder();
        int i = 0;
        while (true) {
            int lo = i < lengthOf(prev) ? digitAt(prev, i) : 0;
            int hi = i < lengthOf(next) ? digitAt(next, i) : INFINITY;

            boolean foundRoom = hi - lo > 1;
            // Either the digit that fits (stopping here) or the shared/lower
            // digit to carry forward while going one position deeper.
            result.append(ALPHABET.charAt(foundRoom ? lo + (hi - lo) / 2 : lo));

            if (result.length() > MAX_RANK_LENGTH) {
                throw new RankExhaustionException(prev, next);
            }
            if (foundRoom) {
                return result.toString();
            }
            i++;
        }
    }

    /**
     * Generates {@code count} distinct ranks in ascending order, spaced by
     * recursive bisection rather than sequentially — see class Javadoc
     * "Rank exhaustion and rebalancing" for why that keeps results short.
     * This is the rebalance primitive: recompute a list's ranks with
     * {@code spacedRanks(list.size())} and reassign them in order.
     *
     * @throws IllegalArgumentException if {@code count} is negative
     */
    public static List<String> spacedRanks(int count) {
        if (count < 0) {
            throw new IllegalArgumentException("count must be >= 0, was " + count);
        }
        String[] ranks = new String[count];
        assignBalanced(ranks, 0, count - 1, null, null);
        return List.of(ranks);
    }

    /**
     * Assigns ranks[from..to] in ascending order, all strictly between
     * {@code lowerBound} and {@code upperBound}, by placing the middle
     * index's rank first and recursing on each half with that rank as the
     * new bound. This bisection order — rather than filling left-to-right —
     * is what keeps every generated rank within O(log₃₆ count) characters.
     */
    private static void assignBalanced(String[] ranks, int from, int to, String lowerBound, String upperBound) {
        if (from > to) {
            return;
        }
        int mid = from + (to - from) / 2;
        String rank = between(lowerBound, upperBound);
        ranks[mid] = rank;
        assignBalanced(ranks, from, mid - 1, lowerBound, rank);
        assignBalanced(ranks, mid + 1, to, rank, upperBound);
    }

    private static int lengthOf(String s) {
        return s == null ? 0 : s.length();
    }

    private static int digitAt(String s, int index) {
        int value = ALPHABET.indexOf(s.charAt(index));
        if (value < 0) {
            throw new IllegalArgumentException(
                    "Rank '%s' contains a character outside the alphabet '%s'".formatted(s, ALPHABET));
        }
        return value;
    }
}
