/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/workspaces/{workspaceId}/cards/{cardId}/labels/{labelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Attach a label to a card (idempotent) */
        put: operations["attachLabel"];
        post?: never;
        /** Detach a label from a card (idempotent) */
        delete: operations["detachLabel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List workspaces the caller belongs to */
        get: operations["listMyWorkspaces"];
        put?: never;
        /** Create a workspace; the caller becomes its OWNER */
        post: operations["createWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/boards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all non-archived boards in a workspace */
        get: operations["listBoards"];
        put?: never;
        /** Create a board, seeded with the default lists */
        post: operations["createBoard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/boards/{boardKey}/lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a list at the end of a board */
        post: operations["createList"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/boards/{boardKey}/lists/{listId}/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a list's live cards in display order */
        get: operations["listCards"];
        put?: never;
        /** Create a card at the end of a list */
        post: operations["createCard"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/boards/{boardKey}/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a board's labels */
        get: operations["listLabels_1"];
        put?: never;
        /** Create a label on a board */
        post: operations["createLabel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an account and receive a token pair */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rotate a refresh token for a new token pair */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a refresh token's session (and its whole rotation family) */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Exchange credentials for a token pair */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one workspace */
        get: operations["getWorkspace"];
        put?: never;
        post?: never;
        /** Delete a workspace and everything in it — OWNER only */
        delete: operations["deleteWorkspace"];
        options?: never;
        head?: never;
        /** Rename a workspace */
        patch: operations["updateWorkspace"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/cards/{cardId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one card */
        get: operations["getCard"];
        put?: never;
        post?: never;
        /** Soft-delete a card */
        delete: operations["deleteCard"];
        options?: never;
        head?: never;
        /**
         * Update a card
         * @description Optimistic locking: `version` must match the card's current version, or this returns 409 with the card's current state in the body.
         */
        patch: operations["updateCard"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/cards/{cardId}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Move a card into a list, landing it between two given neighbours */
        patch: operations["moveCard"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/boards/{boardKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch one board with its lists and cards */
        get: operations["getBoard"];
        put?: never;
        post?: never;
        /** Soft-delete a board */
        delete: operations["deleteBoard"];
        options?: never;
        head?: never;
        /** Rename, redescribe, or (un)archive a board */
        patch: operations["updateBoard"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/boards/{boardKey}/lists/{listId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a list and its cards */
        delete: operations["deleteList"];
        options?: never;
        head?: never;
        /**
         * Update a list
         * @description Optimistic locking: `version` must match the list's current version, or this returns 409 with the list's current state in the body.
         */
        patch: operations["updateList"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/boards/{boardKey}/lists/{listId}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Reorder a list, landing it between two given neighbours */
        patch: operations["moveList"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/boards/{boardKey}/labels/{labelId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a label, removing it from every card that carries it */
        delete: operations["deleteLabel"];
        options?: never;
        head?: never;
        /** Rename or recolor a label */
        patch: operations["updateLabel"];
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/cards/{cardId}/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the labels attached to a card */
        get: operations["listLabels"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch the authenticated user's own profile */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AuthenticatedUser: {
            /** Format: uuid */
            id?: string;
            email?: string;
        };
        CreateWorkspaceRequest: {
            slug: string;
            name: string;
        };
        WorkspaceResponse: {
            /** Format: uuid */
            id?: string;
            slug?: string;
            name?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateBoardRequest: {
            boardKey: string;
            name: string;
            description?: string;
        };
        BoardDetailResponse: {
            /** Format: uuid */
            id?: string;
            boardKey?: string;
            name?: string;
            description?: string;
            archived?: boolean;
            lists?: components["schemas"]["BoardListResponse"][];
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        BoardListResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            rank?: string;
            /** Format: int32 */
            wipLimit?: number;
            /** Format: int64 */
            version?: number;
            cards?: components["schemas"]["CardResponse"][];
        };
        CardResponse: {
            /** Format: uuid */
            id?: string;
            title?: string;
            description?: string;
            rank?: string;
            /** @enum {string} */
            priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
            /** Format: date-time */
            dueAt?: string;
            /** Format: int64 */
            version?: number;
        };
        CreateBoardListRequest: {
            name: string;
            /** Format: int32 */
            wipLimit?: number;
        };
        CreateCardRequest: {
            title: string;
            description?: string;
            /** @enum {string} */
            priority?: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
            /** Format: date-time */
            dueAt?: string;
        };
        CreateLabelRequest: {
            name: string;
            color: string;
        };
        LabelResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            color?: string;
        };
        RegisterRequest: {
            email: string;
            password: string;
            displayName: string;
        };
        TokenPairResponse: {
            accessToken?: string;
            refreshToken?: string;
            /** Format: int64 */
            accessTokenExpiresInSeconds?: number;
            user?: components["schemas"]["UserSummaryResponse"];
        };
        UserSummaryResponse: {
            /** Format: uuid */
            id?: string;
            email?: string;
            displayName?: string;
        };
        RefreshRequest: {
            refreshToken: string;
        };
        LogoutRequest: {
            refreshToken: string;
        };
        LoginRequest: {
            email: string;
            password: string;
        };
        UpdateWorkspaceRequest: {
            name: string;
        };
        UpdateCardRequest: {
            title: string;
            description?: string;
            /** @enum {string} */
            priority: "LOW" | "MEDIUM" | "HIGH" | "URGENT";
            /** Format: date-time */
            dueAt?: string;
            /** Format: int64 */
            version: number;
        };
        MoveCardRequest: {
            /** Format: uuid */
            targetListId: string;
            /** Format: uuid */
            previousCardId?: string;
            /** Format: uuid */
            nextCardId?: string;
        };
        UpdateBoardRequest: {
            name: string;
            description?: string;
            archived?: boolean;
        };
        UpdateBoardListRequest: {
            name: string;
            /** Format: int32 */
            wipLimit?: number;
            /** Format: int64 */
            version: number;
        };
        MoveBoardListRequest: {
            /** Format: uuid */
            previousListId?: string;
            /** Format: uuid */
            nextListId?: string;
        };
        UpdateLabelRequest: {
            name: string;
            color: string;
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        PageResponseWorkspaceResponse: {
            content?: components["schemas"]["WorkspaceResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        BoardSummaryResponse: {
            /** Format: uuid */
            id?: string;
            boardKey?: string;
            name?: string;
            description?: string;
            archived?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        PageResponseBoardSummaryResponse: {
            content?: components["schemas"]["BoardSummaryResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        PageResponseCardResponse: {
            content?: components["schemas"]["CardResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
        PageResponseLabelResponse: {
            content?: components["schemas"]["LabelResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    attachLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                cardId: string;
                labelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    detachLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                cardId: string;
                labelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listMyWorkspaces: {
        parameters: {
            query: {
                currentUser: components["schemas"]["AuthenticatedUser"];
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseWorkspaceResponse"];
                };
            };
        };
    };
    createWorkspace: {
        parameters: {
            query: {
                currentUser: components["schemas"]["AuthenticatedUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkspaceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceResponse"];
                };
            };
        };
    };
    listBoards: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseBoardSummaryResponse"];
                };
            };
        };
    };
    createBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBoardRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BoardDetailResponse"];
                };
            };
        };
    };
    createList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                boardKey: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBoardListRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BoardListResponse"];
                };
            };
        };
    };
    listCards: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                workspaceId: string;
                boardKey: string;
                listId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseCardResponse"];
                };
            };
        };
    };
    createCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                boardKey: string;
                listId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCardRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CardResponse"];
                };
            };
        };
    };
    listLabels_1: {
        parameters: {
            query: {
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                workspaceId: string;
                boardKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PageResponseLabelResponse"];
                };
            };
        };
    };
    createLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                boardKey: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLabelRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LabelResponse"];
                };
            };
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenPairResponse"];
                };
            };
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenPairResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["TokenPairResponse"];
                };
            };
        };
    };
    getWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceResponse"];
                };
            };
        };
    };
    deleteWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkspaceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["WorkspaceResponse"];
                };
            };
        };
    };
    getCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                cardId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CardResponse"];
                };
            };
        };
    };
    deleteCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                cardId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                cardId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCardRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CardResponse"];
                };
            };
        };
    };
    moveCard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                cardId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveCardRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CardResponse"];
                };
            };
        };
    };
    getBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                boardKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BoardDetailResponse"];
                };
            };
        };
    };
    deleteBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                boardKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateBoard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                boardKey: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBoardRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BoardDetailResponse"];
                };
            };
        };
    };
    deleteList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                boardKey: string;
                listId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                boardKey: string;
                listId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBoardListRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BoardListResponse"];
                };
            };
        };
    };
    moveList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                boardKey: string;
                listId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveBoardListRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["BoardListResponse"];
                };
            };
        };
    };
    deleteLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                boardKey: string;
                labelId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateLabel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                boardKey: string;
                labelId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLabelRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LabelResponse"];
                };
            };
        };
    };
    listLabels: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
                cardId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LabelResponse"][];
                };
            };
        };
    };
    me: {
        parameters: {
            query: {
                currentUser: components["schemas"]["AuthenticatedUser"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UserSummaryResponse"];
                };
            };
        };
    };
}
